
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gwen
 */
public class Agence_Aide_jframe extends javax.swing.JFrame {

    /**
     * Creates new form Agence_Aide_jframe
     */
    //javaconnect conn = new javaconnect();
    Connection conn = null;
    ResultSet Rs;
    PreparedStatement pst;
    MyTableModel model = new MyTableModel();
    
    private String numero_agence_aide;
    
    public Agence_Aide_jframe() {
        
        conn = javaconnect.ConnectDb();
        
        model.addColumn("Nom");
        model.addColumn("Adresse");
        model.addColumn("CP");
        model.addColumn("Ville");
        model.addColumn("Télephone");
        model.addColumn("Fax");
        model.addColumn("Mail");
        model.addColumn("Actif");
        model.addColumn("N°");
        //model.addColumn("pays");
        String sql_query = ("SELECT * FROM agence ORDER BY nom");
        try{
            pst = conn.prepareStatement(sql_query);
            Rs = pst.executeQuery();
            while(Rs.next()){
                String actif;
                if (Rs.getInt("actif") == 1){
                    actif = "Oui";
                }
                else{
                    actif = "Non";
                }
                model.addRow(new Object[]{Rs.getString("nom"), Rs.getString("adr1"),
                Rs.getString("cp"), Rs.getString("ville"), Rs.getString("tel_ag"),
                Rs.getString("fax_ag"), Rs.getString("mail_ag"), actif, Rs.getInt("numero")/* Rs.getString("pays")*/});
                }
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        initComponents();
        this.setSize(1310,810 );

        if (Principal_jframe.choix_option_agence == 0){
            Principal_jframe.button_agence_afficher.setEnabled(false);
            Principal_jframe.button_agence_ajouter.setEnabled(false);
            Principal_jframe.button_agence_mod_supp.setEnabled(false);
            
            Principal_jframe.button_utilisateur_ajouter.setEnabled(false);
            Principal_jframe.button_utilisateur_supprimer.setEnabled(false);
            Principal_jframe.button_mon_compte.setEnabled(false);

            Principal_jframe.button_sav_afficher.setEnabled(false);
            Principal_jframe.button_sav_ajouter.setEnabled(false);
            Principal_jframe.button_sav_mod_supp.setEnabled(false);
            
        }






        table_aide.setModel(model);

        table_aide.getColumnModel().getColumn(0).setPreferredWidth(260);
        table_aide.getColumnModel().getColumn(1).setPreferredWidth(230);
        table_aide.getColumnModel().getColumn(2).setPreferredWidth(60);
        table_aide.getColumnModel().getColumn(3).setPreferredWidth(190);
        table_aide.getColumnModel().getColumn(4).setPreferredWidth(100);
        table_aide.getColumnModel().getColumn(5).setPreferredWidth(100);
        table_aide.getColumnModel().getColumn(6).setPreferredWidth(320);
        table_aide.getColumnModel().getColumn(7).setPreferredWidth(40);
        table_aide.getColumnModel().getColumn(8).setPreferredWidth(40);

        table_aide.isCellEditable(WIDTH, WIDTH);
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_aide = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        button_menu_imprimer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Liste des agences");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        table_aide.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Adresse", "CP", "Ville", "Télephone", "Fax", "Mail", "N°"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_aide.setFillsViewportHeight(true);
        table_aide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_aideMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_aide);

        jMenu1.setText("Fichier");

        button_menu_imprimer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        button_menu_imprimer.setText("Imprimer");
        button_menu_imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_menu_imprimerActionPerformed(evt);
            }
        });
        jMenu1.add(button_menu_imprimer);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Principal_jframe.button_agence_afficher.setEnabled(true);
        Principal_jframe.button_agence_ajouter.setEnabled(true);
        Principal_jframe.button_agence_mod_supp.setEnabled(true);
        
        Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
        Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
        Principal_jframe.button_mon_compte.setEnabled(true);

        Principal_jframe.button_sav_afficher.setEnabled(true);
        Principal_jframe.button_sav_ajouter.setEnabled(true);
        Principal_jframe.button_sav_mod_supp.setEnabled(true);
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

   
    private void table_aideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_aideMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2){
            
            try{
                int row = table_aide.getSelectedRow();
                String table_click = (table_aide.getModel().getValueAt(row, 8).toString());
                conn = javaconnect.ConnectDb();
                String sql_click_agence = ("SELECT numero FROM agence WHERE numero = '"+table_click+"';");
                pst = conn.prepareStatement(sql_click_agence);
                Rs = pst.executeQuery();
                if(Rs.next()){
                    if (Principal_jframe.choix_option_agence == 0){
                        numero_agence_aide = Rs.getString("numero");
                        Agence_jframe.numero_agence_affichage = numero_agence_aide;
                        
                        Agence_jframe fenetre_agence = new Agence_jframe();
                        fenetre_agence.setLocationRelativeTo(null);
                        fenetre_agence.setVisible(true);
                    }
                    else{
                        numero_agence_aide = Rs.getString("numero");
                        Agence_jframe.setNumero_agence(numero_agence_aide);
                    }
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            this.dispose();
            
        }
    }//GEN-LAST:event_table_aideMouseClicked

    private void button_menu_imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_menu_imprimerActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Rapport d''impression des agences.");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try{
            PrintRequestAttributeSet asset = new HashPrintRequestAttributeSet();
            asset.add(OrientationRequested.LANDSCAPE);
            //asset.add(new MediaPrintableArea(0.25f,0.25f,8.0f,10.5f,MediaPrintableArea.INCH));
            table_aide.print(JTable.PrintMode.FIT_WIDTH,header, footer, rootPaneCheckingEnabled, asset, rootPaneCheckingEnabled); 
        }
        catch (java.awt.print.PrinterException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_button_menu_imprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agence_Aide_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agence_Aide_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agence_Aide_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agence_Aide_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agence_Aide_jframe().setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem button_menu_imprimer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_aide;
    // End of variables declaration//GEN-END:variables
}
