
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gwen
 */
public class Mon_Compte_jframe extends javax.swing.JFrame {

    /**
     * Creates new form Mon_Compte_jframe
     */
    Connection conn = null;
    ResultSet Rs;
    PreparedStatement pst;
    
    public Mon_Compte_jframe() {
        initComponents();
        
        Principal_jframe.button_utilisateur_ajouter.setEnabled(false);
        Principal_jframe.button_utilisateur_supprimer.setEnabled(false);
        Principal_jframe.button_mon_compte.setEnabled(false);
        
        Principal_jframe.button_agence_afficher.setEnabled(false);
        Principal_jframe.button_agence_ajouter.setEnabled(false);
        Principal_jframe.button_agence_mod_supp.setEnabled(false);
        
        Principal_jframe.button_sav_afficher.setEnabled(false);
        Principal_jframe.button_sav_ajouter.setEnabled(false);
        Principal_jframe.button_sav_mod_supp.setEnabled(false);
        
        txt_user.setDocument(new testDocument(10));
        txt_pass.setDocument(new testDocument(10));
        txt_pass_confirm.setDocument(new testDocument(10));
        txt_libuser.setDocument(new testDocument(30));
        txt_code_fact.setDocument(new testDocument(3));
        txt_opti.setDocument(new testDocument(10));
        
        panel_mot_de_passe.setVisible(false);
        
        
        Afficher_info_user();
    }
    
    private void Afficher_info_user(){
        try{
          conn = javaconnect.ConnectDb();
            String sql_user_afficher = ("SELECT * FROM utilisateur WHERE user = '"+Login_jframe.getUtilisateur_conn()+"';");
            pst = conn.prepareStatement(sql_user_afficher);
            Rs = pst.executeQuery();
            if (Rs.next()){
                txt_user.setText(Rs.getString("user"));
                //txt_pass.setText(Rs.getString("pass"));
                //txt_pass_confirm.setText(Rs.getString("pass"));
                txt_libuser.setText(Rs.getString("libuser"));
                txt_code_fact.setText(Rs.getString("code_fact"));
                txt_opti.setText(Rs.getString("opti"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_libuser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_code_fact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_opti = new javax.swing.JTextField();
        button_modifier = new javax.swing.JButton();
        button_Quitter = new javax.swing.JButton();
        panel_mot_de_passe = new javax.swing.JPanel();
        txt_pass_ancien = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        txt_pass_confirm = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        button_mdp_on_off = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mon compte");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Utilisateur* :");

        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_userKeyPressed(evt);
            }
        });

        txt_libuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_libuserKeyPressed(evt);
            }
        });

        jLabel4.setText("Prenom :");

        jLabel5.setText("Code facturation :");

        txt_code_fact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_code_factKeyPressed(evt);
            }
        });

        jLabel6.setText("Opti :");

        txt_opti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_optiKeyPressed(evt);
            }
        });

        button_modifier.setText("Modifier (F6)");
        button_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_modifierActionPerformed(evt);
            }
        });
        button_modifier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button_modifierKeyPressed(evt);
            }
        });

        button_Quitter.setText("Quitter");
        button_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_QuitterActionPerformed(evt);
            }
        });
        button_Quitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button_QuitterKeyPressed(evt);
            }
        });

        panel_mot_de_passe.setBackground(new java.awt.Color(102, 0, 255));
        panel_mot_de_passe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        txt_pass_ancien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pass_ancienKeyPressed(evt);
            }
        });

        jLabel2.setText("Nouveau :");

        jLabel3.setText("Confirmation :");

        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });

        txt_pass_confirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pass_confirmKeyPressed(evt);
            }
        });

        jLabel7.setText("Ancien :");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_fond/1797393.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout panel_mot_de_passeLayout = new javax.swing.GroupLayout(panel_mot_de_passe);
        panel_mot_de_passe.setLayout(panel_mot_de_passeLayout);
        panel_mot_de_passeLayout.setHorizontalGroup(
            panel_mot_de_passeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mot_de_passeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_mot_de_passeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mot_de_passeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pass_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mot_de_passeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel_mot_de_passeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_mot_de_passeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_pass_ancien)
                            .addComponent(txt_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
            .addGroup(panel_mot_de_passeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, Short.MAX_VALUE))
        );
        panel_mot_de_passeLayout.setVerticalGroup(
            panel_mot_de_passeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mot_de_passeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_mot_de_passeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass_ancien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_mot_de_passeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_mot_de_passeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pass_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_mot_de_passeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, Short.MAX_VALUE))
        );

        button_mdp_on_off.setText("Changer le mot de passe (F2)");
        button_mdp_on_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mdp_on_offActionPerformed(evt);
            }
        });
        button_mdp_on_off.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button_mdp_on_offKeyPressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_fond/1797393.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel10.setText("* Champ obligatoire");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_libuser)
                                    .addComponent(txt_code_fact)
                                    .addComponent(txt_opti)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(button_mdp_on_off, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_mot_de_passe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(button_modifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_Quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 475, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_mdp_on_off)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_libuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_code_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_opti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(panel_mot_de_passe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
        Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
        Principal_jframe.button_mon_compte.setEnabled(true);
        
        Principal_jframe.button_agence_afficher.setEnabled(true);
        Principal_jframe.button_agence_ajouter.setEnabled(true);
        Principal_jframe.button_agence_mod_supp.setEnabled(true);
        
        Principal_jframe.button_sav_afficher.setEnabled(true);
        Principal_jframe.button_sav_ajouter.setEnabled(true);
        Principal_jframe.button_sav_mod_supp.setEnabled(true);
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing
    
    public void Modifier_user(){
        if (button_on_off == 1){
            if (Login_jframe.getUtilisateur_conn().equals(txt_user.getText())){
                try{
                    conn = javaconnect.ConnectDb();
                    String sql_verif_mdp_ancien = ("SELECT user,pass FROM utilisateur WHERE user = '"+Login_jframe.getUtilisateur_conn()+"';");
                    pst = conn.prepareStatement(sql_verif_mdp_ancien);
                    Rs = pst.executeQuery();
                    if (Rs.next()){
                        if (Rs.getString("pass").equals(txt_pass_ancien.getText())){
                            if (txt_pass.getText().equals(txt_pass_confirm.getText())){
                                try{
                                    conn = javaconnect.ConnectDb();
                                    String sql_modifier_utilisateur = ("UPDATE utilisateur SET user = '"+txt_user.getText().replace("'", "''")+"',pass = '"+txt_pass.getText().replace("'", "''")+
                                        "',libuser = '"+txt_libuser.getText().replace("'", "''")+
                                        "',code_fact = '"+txt_code_fact.getText().replace("'", "''")+"',opti = '"+txt_opti.getText().replace("'", "''")+
                                        "' WHERE user = '"+Login_jframe.getUtilisateur_conn()+"';");
                                    pst = conn.prepareStatement(sql_modifier_utilisateur);
                                    pst.executeUpdate();
                                    Afficher_info_user();
                                    JOptionPane.showMessageDialog(null, "Votre compte a été modifié avec succès.");
                                    Login_jframe.utilisateur_conn = txt_user.getText();
                                    Login_jframe.libUser = txt_libuser.getText();
                                    Principal_jframe.jLabel2.setText("Bienvenue " + Login_jframe.libUser);
                                    Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
                                    Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
                                    Principal_jframe.button_mon_compte.setEnabled(true);
                                    
                                    Principal_jframe.button_agence_afficher.setEnabled(true);
                                    Principal_jframe.button_agence_ajouter.setEnabled(true);
                                    Principal_jframe.button_agence_mod_supp.setEnabled(true);

                                    Principal_jframe.button_sav_afficher.setEnabled(true);
                                    Principal_jframe.button_sav_ajouter.setEnabled(true);
                                    Principal_jframe.button_sav_mod_supp.setEnabled(true);
        
                                    this.dispose();
                                }
                                catch(Exception e){
                                   JOptionPane.showMessageDialog(null, e);
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Confirmation du mot de passe incorrecte.");
                                txt_pass.setText("");
                                txt_pass_confirm.setText("");
                                txt_pass.requestFocus();
                                
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Erreur sur l'ancien mot de passe.");
                            txt_pass_ancien.setText("");
                            txt_pass_ancien.requestFocus();
                        }
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }  
            }
            else{
                try{
                    conn = javaconnect.ConnectDb();
                    String sql_verif_mdp_ancien = ("SELECT user,pass FROM utilisateur WHERE user = '"+Login_jframe.getUtilisateur_conn()+"';");
                    pst = conn.prepareStatement(sql_verif_mdp_ancien);
                    Rs = pst.executeQuery();
                    if (Rs.next()){
                        if (Rs.getString("pass").equals(txt_pass_ancien.getText())){
                            if (txt_pass.getText().equals(txt_pass_confirm.getText())){
                                try{
                                    conn = javaconnect.ConnectDb();
                                    String sql_user_exist_verif = ("SELECT user FROM utilisateur WHERE user = '"+txt_user.getText()+"';");
                                    pst = conn.prepareStatement(sql_user_exist_verif);
                                    Rs = pst.executeQuery();
                                    if (Rs.next()){
                                        JOptionPane.showMessageDialog(null, "Ce nom d'utilisateur existe déjà.");
                                        txt_user.requestFocus();
                                    }
                                    else{
                                        String sql_modifier_utilisateur = ("UPDATE utilisateur SET user = '"+txt_user.getText().replace("'", "''")+"',pass = '"+txt_pass.getText().replace("'", "''")+
                                            "',libuser = '"+txt_libuser.getText().replace("'", "''")+
                                            "',code_fact = '"+txt_code_fact.getText().replace("'", "''")+"',opti = '"+txt_opti.getText().replace("'", "''")+
                                            "' WHERE user = '"+Login_jframe.getUtilisateur_conn()+"';");
                                        pst = conn.prepareStatement(sql_modifier_utilisateur);
                                        pst.executeUpdate();
                                        Afficher_info_user();
                                        JOptionPane.showMessageDialog(null, "Utilisateur modifié avec succès.");
                                        Login_jframe.utilisateur_conn = txt_user.getText();
                                        Login_jframe.libUser = txt_libuser.getText();
                                        Principal_jframe.jLabel2.setText("Bienvenue " + Login_jframe.libUser);
                                        Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
                                        Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
                                        Principal_jframe.button_mon_compte.setEnabled(true);
                                        
                                        Principal_jframe.button_agence_afficher.setEnabled(true);
                                        Principal_jframe.button_agence_ajouter.setEnabled(true);
                                        Principal_jframe.button_agence_mod_supp.setEnabled(true);

                                        Principal_jframe.button_sav_afficher.setEnabled(true);
                                        Principal_jframe.button_sav_ajouter.setEnabled(true);
                                        Principal_jframe.button_sav_mod_supp.setEnabled(true);
                                        
                                        this.dispose();
                                    }        
                                }
                                catch(Exception e){
                                   JOptionPane.showMessageDialog(null, e);
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Confirmation du mot de passe incorrecte.");
                                txt_pass.setText("");
                                txt_pass_confirm.setText("");
                                txt_pass.requestFocus();
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Erreur sur l'ancien mot de passe.");
                            txt_pass_ancien.setText("");
                            txt_pass_ancien.requestFocus();
                        }
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            
            
            
            
            
            
        }
        else{
            if (Login_jframe.getUtilisateur_conn().equals(txt_user.getText())){
                try{
                    conn = javaconnect.ConnectDb();
                    String sql_modifier_utilisateur = ("UPDATE utilisateur SET user = '"+txt_user.getText().replace("'", "''")+
                        "',libuser = '"+txt_libuser.getText().replace("'", "''")+
                        "',code_fact = '"+txt_code_fact.getText().replace("'", "''")+"',opti = '"+txt_opti.getText().replace("'", "''")+
                        "' WHERE user = '"+Login_jframe.getUtilisateur_conn()+"';");
                    pst = conn.prepareStatement(sql_modifier_utilisateur);
                    pst.executeUpdate();
                    Afficher_info_user();
                    JOptionPane.showMessageDialog(null, "Utilisateur modifié avec succès.");
                    Login_jframe.utilisateur_conn = txt_user.getText();
                    Login_jframe.libUser = txt_libuser.getText();
                    Principal_jframe.jLabel2.setText("Bienvenue " + Login_jframe.libUser);
                    Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
                    Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
                    Principal_jframe.button_mon_compte.setEnabled(true);
                    
                    Principal_jframe.button_agence_afficher.setEnabled(true);
                    Principal_jframe.button_agence_ajouter.setEnabled(true);
                    Principal_jframe.button_agence_mod_supp.setEnabled(true);

                    Principal_jframe.button_sav_afficher.setEnabled(true);
                    Principal_jframe.button_sav_ajouter.setEnabled(true);
                    Principal_jframe.button_sav_mod_supp.setEnabled(true);
        
                    this.dispose();
                }
                catch(Exception e){
                   JOptionPane.showMessageDialog(null, e);
                }
            }
            else{
                try{
                    conn = javaconnect.ConnectDb();
                    String sql_user_exist_verif = ("SELECT user FROM utilisateur WHERE user = '"+txt_user.getText()+"';");
                    pst = conn.prepareStatement(sql_user_exist_verif);
                    Rs = pst.executeQuery();
                    if (Rs.next()){
                        JOptionPane.showMessageDialog(null, "Ce nom d'utilisateur existe déjà.");
                        txt_user.requestFocus();
                    }
                    else{
                        String sql_modifier_utilisateur = ("UPDATE utilisateur SET user = '"+txt_user.getText().replace("'", "''")+
                            "',libuser = '"+txt_libuser.getText().replace("'", "''")+
                            "',code_fact = '"+txt_code_fact.getText()+"',opti = '"+txt_opti.getText().replace("'", "''")+
                            "' WHERE user = '"+Login_jframe.getUtilisateur_conn()+"';");
                        pst = conn.prepareStatement(sql_modifier_utilisateur);
                        pst.executeUpdate();
                        Afficher_info_user();
                        JOptionPane.showMessageDialog(null, "Utilisateur modifié avec succès.");
                        Login_jframe.utilisateur_conn = txt_user.getText();
                        Login_jframe.libUser = txt_libuser.getText();
                        Principal_jframe.jLabel2.setText("Bienvenue " + Login_jframe.libUser);
                        Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
                        Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
                        Principal_jframe.button_mon_compte.setEnabled(true);
                        
                        Principal_jframe.button_agence_afficher.setEnabled(true);
                        Principal_jframe.button_agence_ajouter.setEnabled(true);
                        Principal_jframe.button_agence_mod_supp.setEnabled(true);

                        Principal_jframe.button_sav_afficher.setEnabled(true);
                        Principal_jframe.button_sav_ajouter.setEnabled(true);
                        Principal_jframe.button_sav_mod_supp.setEnabled(true);
                        
                        this.dispose();
                    }        
                }
                catch(Exception e){
                   JOptionPane.showMessageDialog(null, e);
                } 
            }
        }
            
    }
    
    private void button_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_modifierActionPerformed
        // TODO add your handling code here:
        Modifier_user();
    }//GEN-LAST:event_button_modifierActionPerformed

    private void button_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_QuitterActionPerformed
        // TODO add your handling code here:
        Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
        Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
        Principal_jframe.button_mon_compte.setEnabled(true);
        
        Principal_jframe.button_agence_afficher.setEnabled(true);
        Principal_jframe.button_agence_ajouter.setEnabled(true);
        Principal_jframe.button_agence_mod_supp.setEnabled(true);
        
        Principal_jframe.button_sav_afficher.setEnabled(true);
        Principal_jframe.button_sav_ajouter.setEnabled(true);
        Principal_jframe.button_sav_mod_supp.setEnabled(true);
        
        this.dispose();
    }//GEN-LAST:event_button_QuitterActionPerformed

    private int button_on_off = 0;
    
    public void button_mdp_on_ou_off(){
        if (button_on_off == 0){
            panel_mot_de_passe.setVisible(true);
            button_on_off = 1;
        }
        else{
            panel_mot_de_passe.setVisible(false);
            button_on_off = 0;
        }
    }
    
    private void button_mdp_on_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mdp_on_offActionPerformed
        // TODO add your handling code here:
        button_mdp_on_ou_off();
    }//GEN-LAST:event_button_mdp_on_offActionPerformed

    private void txt_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            if (button_on_off == 0){
                txt_libuser.requestFocus();
            }
            else{
                txt_pass_ancien.requestFocus();
            }
        }
        if (c == KeyEvent.VK_F2){
            button_mdp_on_ou_off();
        }
        if (c == KeyEvent.VK_F4){
            Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
            Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
            Principal_jframe.button_mon_compte.setEnabled(true);
            
            Principal_jframe.button_agence_afficher.setEnabled(true);
            Principal_jframe.button_agence_ajouter.setEnabled(true);
            Principal_jframe.button_agence_mod_supp.setEnabled(true);

            Principal_jframe.button_sav_afficher.setEnabled(true);
            Principal_jframe.button_sav_ajouter.setEnabled(true);
            Principal_jframe.button_sav_mod_supp.setEnabled(true);
            
            this.dispose();
        }
        if (c == KeyEvent.VK_F6){
            Modifier_user();
        }
    }//GEN-LAST:event_txt_userKeyPressed

    private void button_mdp_on_offKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_mdp_on_offKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            button_mdp_on_ou_off();
        }
        if (c == KeyEvent.VK_F2){
            button_mdp_on_ou_off();
        }
        if (c == KeyEvent.VK_F4){
            button_mdp_on_off.transferFocusBackward();;
        }
        if (c == KeyEvent.VK_F6){
            Modifier_user();
        }
    }//GEN-LAST:event_button_mdp_on_offKeyPressed

    private void txt_pass_ancienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pass_ancienKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            txt_pass_ancien.transferFocus();
        }
        if (c == KeyEvent.VK_F2){
            button_mdp_on_ou_off();
        }
        if (c == KeyEvent.VK_F4){
            txt_pass_ancien.transferFocusBackward();;
        }
        if (c == KeyEvent.VK_F6){
            Modifier_user();
        }
    }//GEN-LAST:event_txt_pass_ancienKeyPressed

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            txt_pass.transferFocus();
        }
        if (c == KeyEvent.VK_F2){
            button_mdp_on_ou_off();
        }
        if (c == KeyEvent.VK_F4){
            txt_pass.transferFocusBackward();;
        }
        if (c == KeyEvent.VK_F6){
            Modifier_user();
        }
        
    }//GEN-LAST:event_txt_passKeyPressed

    private void txt_pass_confirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pass_confirmKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            txt_libuser.requestFocus();
        }
        if (c == KeyEvent.VK_F2){
            button_mdp_on_ou_off();
        }
        if (c == KeyEvent.VK_F4){
            txt_pass_confirm.transferFocusBackward();;
        }
        if (c == KeyEvent.VK_F6){
            Modifier_user();
        }
    }//GEN-LAST:event_txt_pass_confirmKeyPressed

    private void txt_libuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_libuserKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            txt_libuser.transferFocus();
        }
        if (c == KeyEvent.VK_F2){
            button_mdp_on_ou_off();
        }
        if (c == KeyEvent.VK_F4){
            txt_libuser.transferFocusBackward();;
        }
        if (c == KeyEvent.VK_F6){
            Modifier_user();
        }
    }//GEN-LAST:event_txt_libuserKeyPressed

    private void txt_code_factKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_code_factKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            txt_code_fact.transferFocus();
        }
        if (c == KeyEvent.VK_F2){
            button_mdp_on_ou_off();
        }
        if (c == KeyEvent.VK_F4){
            txt_code_fact.transferFocusBackward();;
        }
        if (c == KeyEvent.VK_F6){
            Modifier_user();
        }
    }//GEN-LAST:event_txt_code_factKeyPressed

    private void txt_optiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_optiKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            txt_opti.transferFocus();
        }
        if (c == KeyEvent.VK_F2){
            button_mdp_on_ou_off();
        }
        if (c == KeyEvent.VK_F4){
            txt_opti.transferFocusBackward();;
        }
        if (c == KeyEvent.VK_F6){
            Modifier_user();
        }
    }//GEN-LAST:event_txt_optiKeyPressed

    private void button_modifierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_modifierKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            Modifier_user();
        }
        if (c == KeyEvent.VK_F4){
            button_modifier.transferFocusBackward();
        }
        if (c == KeyEvent.VK_F6){
            Modifier_user();
        }
    }//GEN-LAST:event_button_modifierKeyPressed

    private void button_QuitterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_QuitterKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
            Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
            Principal_jframe.button_mon_compte.setEnabled(true);
            
            Principal_jframe.button_agence_afficher.setEnabled(true);
            Principal_jframe.button_agence_ajouter.setEnabled(true);
            Principal_jframe.button_agence_mod_supp.setEnabled(true);

            Principal_jframe.button_sav_afficher.setEnabled(true);
            Principal_jframe.button_sav_ajouter.setEnabled(true);
            Principal_jframe.button_sav_mod_supp.setEnabled(true);
            
            this.dispose();
        }
        if (c == KeyEvent.VK_F4){
            button_Quitter.transferFocusBackward();
        }
        if (c == KeyEvent.VK_F6){
            Modifier_user();
        }
    }//GEN-LAST:event_button_QuitterKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mon_Compte_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mon_Compte_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mon_Compte_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mon_Compte_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mon_Compte_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Quitter;
    private javax.swing.JButton button_mdp_on_off;
    private javax.swing.JButton button_modifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel_mot_de_passe;
    private javax.swing.JTextField txt_code_fact;
    private javax.swing.JTextField txt_libuser;
    private javax.swing.JTextField txt_opti;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JPasswordField txt_pass_ancien;
    private javax.swing.JPasswordField txt_pass_confirm;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
