
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gwen
 */
public class Utilisateur_jframe extends javax.swing.JFrame {

    /**
     * Creates new form Utilisateur_jframe
     */
    Connection conn = null;
    ResultSet Rs;
    PreparedStatement pst;
    MyTableModel model = new MyTableModel();
    private String image_par_defaut = "";
    
    
    
    
    private void UpdateTable(){
        model.getDataVector().removeAllElements();
        conn = javaconnect.ConnectDb();
        String sql_query = ("SELECT * FROM utilisateur");
        try{
            pst = conn.prepareStatement(sql_query);
            Rs = pst.executeQuery();
            while(Rs.next()){
                model.addRow(new Object[]{Rs.getString("user"), /*Rs.getString("pass"),*/ Rs.getString("libuser"),
                    Rs.getString("code_fact"), /*Rs.getString("image"), Rs.getString("opti")*/});
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            table_utilisateur.setModel(model);
    }
    
    public Utilisateur_jframe() {
        initComponents();
        
        
        
        if (Principal_jframe.utilisateur_option == 0){
            //table_utilisateur.setEnabled(false);
            Principal_jframe.button_utilisateur_ajouter.setEnabled(false);
            Principal_jframe.button_utilisateur_supprimer.setEnabled(false);
            Principal_jframe.button_mon_compte.setEnabled(false);
            
            Principal_jframe.button_agence_afficher.setEnabled(false);
            Principal_jframe.button_agence_ajouter.setEnabled(false);
            Principal_jframe.button_agence_mod_supp.setEnabled(false);

            Principal_jframe.button_sav_afficher.setEnabled(false);
            Principal_jframe.button_sav_ajouter.setEnabled(false);
            Principal_jframe.button_sav_mod_supp.setEnabled(false);
            
            table_utilisateur.setVisible(false);
            button_supprimer_utilisateur.setVisible(false);
            button_supprimer_quitter.setVisible(false);
            jScrollPane1.setVisible(false);
            this.setSize(620, 180);
        }
        if (Principal_jframe.utilisateur_option == 1){
            Principal_jframe.button_utilisateur_ajouter.setEnabled(false);
            Principal_jframe.button_utilisateur_supprimer.setEnabled(false);
            Principal_jframe.button_mon_compte.setEnabled(false);
            
            Principal_jframe.button_agence_afficher.setEnabled(false);
            Principal_jframe.button_agence_ajouter.setEnabled(false);
            Principal_jframe.button_agence_mod_supp.setEnabled(false);

            Principal_jframe.button_sav_afficher.setEnabled(false);
            Principal_jframe.button_sav_ajouter.setEnabled(false);
            Principal_jframe.button_sav_mod_supp.setEnabled(false);
            
            model.addColumn("Utilisateur");
            //model.addColumn("pass");
            model.addColumn("Prenom");
            model.addColumn("Code de facturation");
            //model.addColumn("image");
            //model.addColumn("opti");
            UpdateTable();
            jPanel1.setVisible(false);
            Principal_jframe.utilisateur_option = 0;
            this.setSize(588, 240);
            button_supprimer_utilisateur.requestFocusInWindow();
        }
        
        txt_user.setDocument(new testDocument(10));
        txt_pass.setDocument(new testDocument(10));
        txt_pass_confirmation.setDocument(new testDocument(10));
        txt_libuser.setDocument(new testDocument(30));
        txt_code_fact.setDocument(new testDocument(3));
        txt_opti.setDocument(new testDocument(10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        txt_pass_confirmation = new javax.swing.JPasswordField();
        txt_libuser = new javax.swing.JTextField();
        txt_code_fact = new javax.swing.JTextField();
        txt_opti = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        button_ajouter_utilisateur = new javax.swing.JButton();
        button_ajout_quitter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        button_supprimer_utilisateur = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_utilisateur = new javax.swing.JTable();
        button_supprimer_quitter = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Utilisateurs");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(234, 234, 234));
        jPanel1.setForeground(new java.awt.Color(233, 233, 233));

        jLabel1.setText("Utilisateur* :");

        jLabel2.setText("Mot de passe :");

        jLabel3.setText("Prenom :");

        txt_user.setNextFocusableComponent(txt_libuser);
        txt_user.setPreferredSize(new java.awt.Dimension(100, 30));
        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_userKeyPressed(evt);
            }
        });

        txt_pass.setNextFocusableComponent(txt_pass_confirmation);
        txt_pass.setPreferredSize(new java.awt.Dimension(100, 30));
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });

        txt_pass_confirmation.setNextFocusableComponent(txt_user);
        txt_pass_confirmation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pass_confirmationKeyPressed(evt);
            }
        });

        txt_libuser.setNextFocusableComponent(txt_code_fact);
        txt_libuser.setPreferredSize(new java.awt.Dimension(100, 30));
        txt_libuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_libuserKeyPressed(evt);
            }
        });

        txt_code_fact.setNextFocusableComponent(txt_opti);
        txt_code_fact.setPreferredSize(new java.awt.Dimension(100, 30));
        txt_code_fact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_code_factKeyPressed(evt);
            }
        });

        txt_opti.setNextFocusableComponent(txt_pass);
        txt_opti.setPreferredSize(new java.awt.Dimension(100, 30));
        txt_opti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_optiKeyPressed(evt);
            }
        });

        jLabel5.setText("Code_fact :");

        jLabel6.setText("Opti :");

        jLabel8.setText("Confirmation :");

        button_ajouter_utilisateur.setText("Ajouter (F6)");
        button_ajouter_utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ajouter_utilisateurActionPerformed(evt);
            }
        });
        button_ajouter_utilisateur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button_ajouter_utilisateurKeyPressed(evt);
            }
        });

        button_ajout_quitter.setText("Quitter");
        button_ajout_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ajout_quitterActionPerformed(evt);
            }
        });
        button_ajout_quitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button_ajout_quitterKeyPressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_fond/1797393.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel10.setText("* Champ obligatoire");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_opti, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_libuser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_pass_confirmation, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_code_fact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(button_ajouter_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_ajout_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 476, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_code_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_libuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass_confirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_opti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_ajouter_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(button_ajout_quitter, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 142, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        button_supprimer_utilisateur.setText("Supprimer");
        button_supprimer_utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_supprimer_utilisateurActionPerformed(evt);
            }
        });
        button_supprimer_utilisateur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button_supprimer_utilisateurKeyPressed(evt);
            }
        });

        table_utilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Utilisateur", "Prenom", "Code de facturation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_utilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_utilisateurMouseClicked(evt);
            }
        });
        table_utilisateur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table_utilisateurKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_utilisateur);

        button_supprimer_quitter.setText("Quitter");
        button_supprimer_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_supprimer_quitterActionPerformed(evt);
            }
        });
        button_supprimer_quitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button_supprimer_quitterKeyPressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_fond/1797393.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_supprimer_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(button_supprimer_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 586, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_supprimer_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_supprimer_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
        Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
        Principal_jframe.button_mon_compte.setEnabled(true);
        
        Principal_jframe.button_agence_afficher.setEnabled(true);
        Principal_jframe.button_agence_ajouter.setEnabled(true);
        Principal_jframe.button_agence_mod_supp.setEnabled(true);
        
        Principal_jframe.button_sav_afficher.setEnabled(true);
        Principal_jframe.button_sav_ajouter.setEnabled(true);
        Principal_jframe.button_sav_mod_supp.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing
    
    public void ajouter_utilisateur(){
        if ("".equals(txt_user.getText())){
            JOptionPane.showMessageDialog(null, "Le champ utilisateur est obligatoire.");
            txt_user.requestFocus();
        }
        else{
            try{
                conn = javaconnect.ConnectDb();
                String sql_user_exist_verif = ("SELECT user FROM utilisateur WHERE user = '"+txt_user.getText()+"';");
                pst = conn.prepareStatement(sql_user_exist_verif);
                Rs = pst.executeQuery();
                if (Rs.next()){
                    JOptionPane.showMessageDialog(null, "Ce nom d'utilisateur existe déjà.");
                    txt_user.requestFocus();
                }
                else{
                    if (txt_pass.getText().equals(txt_pass_confirmation.getText())){
                        int option = JOptionPane.showConfirmDialog(null, "Confirmer l'ajout de l'utilisateur.");
                        if(option == JOptionPane.OK_OPTION){
                            String sql_ajout_utilisateur = ("INSERT INTO utilisateur VALUES('"+txt_user.getText().replace("'", "''")+"','"+txt_pass.getText().replace("'", "''")+"','"+txt_libuser.getText().replace("'", "''")+
                                "','"+txt_code_fact.getText().replace("'", "''")+"','"+image_par_defaut+"','"+txt_opti.getText().replace("'", "''")+"');");
                            pst = conn.prepareStatement(sql_ajout_utilisateur);
                            pst.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Utilisateur ajouté avec succès.");
                            UpdateTable();
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Confirmation du mot de passe incorrecte.");
                        txt_pass.setText("");
                        txt_pass_confirmation.setText("");
                        txt_pass.requestFocus();
                    }
                }  
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    
    private void button_ajouter_utilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ajouter_utilisateurActionPerformed
        // TODO add your handling code here:
           ajouter_utilisateur();
    }//GEN-LAST:event_button_ajouter_utilisateurActionPerformed
    
    public void supprimer_utilisateur(){
        if ("".equals(txt_user.getText())){
            JOptionPane.showMessageDialog(null, "Aucun utilisateur sélectionner.");
        }
        else{
            if (Login_jframe.getUtilisateur_conn().equals(txt_user.getText())){
                JOptionPane.showMessageDialog(null, "Vous ne pouvez pas vous supprimer.");
            }
            else{
                int option = JOptionPane.showConfirmDialog(null, "Confirmer la suppression de l'utilisateur.");
                if(option == JOptionPane.OK_OPTION){
                    try{
                        conn = javaconnect.ConnectDb();
                        String sql_ajout_utilisateur = ("DELETE FROM utilisateur WHERE user = '"+txt_user.getText()+"';");
                        pst = conn.prepareStatement(sql_ajout_utilisateur);
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Utilisateur supprimé avec succès.");
                        UpdateTable();
                    }
                    catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
        }
    }
    
    private void button_supprimer_utilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_supprimer_utilisateurActionPerformed
        // TODO add your handling code here:
        supprimer_utilisateur();
    }//GEN-LAST:event_button_supprimer_utilisateurActionPerformed

    private void table_utilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_utilisateurMouseClicked
        // TODO add your handling code here:
        try{
            int row = table_utilisateur.getSelectedRow();
            String table_click = (table_utilisateur.getModel().getValueAt(row, 0).toString());
            conn = javaconnect.ConnectDb();
            String sql_click_utilisateur = ("SELECT * FROM utilisateur WHERE user = '"+table_click+"';");
            pst = conn.prepareStatement(sql_click_utilisateur);
            Rs = pst.executeQuery();
            if(Rs.next()){
                txt_user.setText(Rs.getString("user"));
                txt_pass.setText(Rs.getString("pass"));
                txt_pass_confirmation.setText(Rs.getString("pass"));
                txt_libuser.setText(Rs.getString("libuser"));
                txt_code_fact.setText(Rs.getString("code_fact"));
                txt_opti.setText(Rs.getString("opti"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_table_utilisateurMouseClicked

    private void txt_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            txt_user.transferFocus();
        }
        if (c == KeyEvent.VK_F4){
            Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
            Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
            Principal_jframe.button_mon_compte.setEnabled(true);
            
            Principal_jframe.button_agence_afficher.setEnabled(true);
            Principal_jframe.button_agence_ajouter.setEnabled(true);
            Principal_jframe.button_agence_mod_supp.setEnabled(true);

            Principal_jframe.button_sav_afficher.setEnabled(true);
            Principal_jframe.button_sav_ajouter.setEnabled(true);
            Principal_jframe.button_sav_mod_supp.setEnabled(true);
            
            this.dispose();
        }
        if (c == KeyEvent.VK_F6){
            ajouter_utilisateur();
        }
        
    }//GEN-LAST:event_txt_userKeyPressed

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            txt_pass.transferFocus();
        }
        if (c == KeyEvent.VK_F4){
            txt_pass.transferFocusBackward();
        }
        if (c == KeyEvent.VK_F6){
            ajouter_utilisateur();
        }
    }//GEN-LAST:event_txt_passKeyPressed

    private void txt_pass_confirmationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pass_confirmationKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            ajouter_utilisateur();
        }
        if (c == KeyEvent.VK_F4){
            txt_pass_confirmation.transferFocusBackward();
        }
        if (c == KeyEvent.VK_F6){
            ajouter_utilisateur();
        }
    }//GEN-LAST:event_txt_pass_confirmationKeyPressed

    private void txt_libuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_libuserKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            txt_libuser.transferFocus();
        }
        if (c == KeyEvent.VK_F4){
            txt_libuser.transferFocusBackward();
        }
        if (c == KeyEvent.VK_F6){
            ajouter_utilisateur();
        }
    }//GEN-LAST:event_txt_libuserKeyPressed

    private void txt_code_factKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_code_factKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            txt_code_fact.transferFocus();
        }
        if (c == KeyEvent.VK_F4){
            txt_code_fact.transferFocusBackward();
        }
        if (c == KeyEvent.VK_F6){
            ajouter_utilisateur();
        }
    }//GEN-LAST:event_txt_code_factKeyPressed

    private void txt_optiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_optiKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            txt_opti.transferFocus();
        }
        if (c == KeyEvent.VK_F4){
            txt_opti.transferFocusBackward();
        }
        if (c == KeyEvent.VK_F6){
            ajouter_utilisateur();
        }
    }//GEN-LAST:event_txt_optiKeyPressed

    private void button_ajouter_utilisateurKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_ajouter_utilisateurKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            ajouter_utilisateur();
        }
        if (c == KeyEvent.VK_F4){
            button_ajouter_utilisateur.transferFocusBackward();
        }
        if (c == KeyEvent.VK_F6){
            ajouter_utilisateur();
        }
    }//GEN-LAST:event_button_ajouter_utilisateurKeyPressed

    private void button_supprimer_utilisateurKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_supprimer_utilisateurKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            supprimer_utilisateur();
        }
        if (c == KeyEvent.VK_F4){
            Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
            Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
            Principal_jframe.button_mon_compte.setEnabled(true);
            
            Principal_jframe.button_agence_afficher.setEnabled(true);
            Principal_jframe.button_agence_ajouter.setEnabled(true);
            Principal_jframe.button_agence_mod_supp.setEnabled(true);

            Principal_jframe.button_sav_afficher.setEnabled(true);
            Principal_jframe.button_sav_ajouter.setEnabled(true);
            Principal_jframe.button_sav_mod_supp.setEnabled(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_button_supprimer_utilisateurKeyPressed

    private void table_utilisateurKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_utilisateurKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_F4){
            Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
            Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
            Principal_jframe.button_mon_compte.setEnabled(true);
            
            Principal_jframe.button_agence_afficher.setEnabled(true);
            Principal_jframe.button_agence_ajouter.setEnabled(true);
            Principal_jframe.button_agence_mod_supp.setEnabled(true);

            Principal_jframe.button_sav_afficher.setEnabled(true);
            Principal_jframe.button_sav_ajouter.setEnabled(true);
            Principal_jframe.button_sav_mod_supp.setEnabled(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_table_utilisateurKeyPressed

    private void button_ajout_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ajout_quitterActionPerformed
        // TODO add your handling code here:
        Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
        Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
        Principal_jframe.button_mon_compte.setEnabled(true);
        
        Principal_jframe.button_agence_afficher.setEnabled(true);
        Principal_jframe.button_agence_ajouter.setEnabled(true);
        Principal_jframe.button_agence_mod_supp.setEnabled(true);

        Principal_jframe.button_sav_afficher.setEnabled(true);
        Principal_jframe.button_sav_ajouter.setEnabled(true);
        Principal_jframe.button_sav_mod_supp.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_button_ajout_quitterActionPerformed

    private void button_ajout_quitterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_ajout_quitterKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
            Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
            Principal_jframe.button_mon_compte.setEnabled(true);
            
            Principal_jframe.button_agence_afficher.setEnabled(true);
            Principal_jframe.button_agence_ajouter.setEnabled(true);
            Principal_jframe.button_agence_mod_supp.setEnabled(true);

            Principal_jframe.button_sav_afficher.setEnabled(true);
            Principal_jframe.button_sav_ajouter.setEnabled(true);
            Principal_jframe.button_sav_mod_supp.setEnabled(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_button_ajout_quitterKeyPressed

    private void button_supprimer_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_supprimer_quitterActionPerformed
        // TODO add your handling code here:
        Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
        Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
        Principal_jframe.button_mon_compte.setEnabled(true);
        
        Principal_jframe.button_agence_afficher.setEnabled(true);
        Principal_jframe.button_agence_ajouter.setEnabled(true);
        Principal_jframe.button_agence_mod_supp.setEnabled(true);

        Principal_jframe.button_sav_afficher.setEnabled(true);
        Principal_jframe.button_sav_ajouter.setEnabled(true);
        Principal_jframe.button_sav_mod_supp.setEnabled(true);
        
        this.dispose();
    }//GEN-LAST:event_button_supprimer_quitterActionPerformed

    private void button_supprimer_quitterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_supprimer_quitterKeyPressed
        // TODO add your handling code here:
        int c = evt.getKeyCode();
        if (c == KeyEvent.VK_ENTER){
            Principal_jframe.button_utilisateur_ajouter.setEnabled(true);
            Principal_jframe.button_utilisateur_supprimer.setEnabled(true);
            Principal_jframe.button_mon_compte.setEnabled(true);
            
            Principal_jframe.button_agence_afficher.setEnabled(true);
            Principal_jframe.button_agence_ajouter.setEnabled(true);
            Principal_jframe.button_agence_mod_supp.setEnabled(true);

            Principal_jframe.button_sav_afficher.setEnabled(true);
            Principal_jframe.button_sav_ajouter.setEnabled(true);
            Principal_jframe.button_sav_mod_supp.setEnabled(true);
            
            this.dispose();
        }
    }//GEN-LAST:event_button_supprimer_quitterKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilisateur_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilisateur_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilisateur_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilisateur_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilisateur_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ajout_quitter;
    private javax.swing.JButton button_ajouter_utilisateur;
    private javax.swing.JButton button_supprimer_quitter;
    private javax.swing.JButton button_supprimer_utilisateur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_utilisateur;
    private javax.swing.JTextField txt_code_fact;
    private javax.swing.JTextField txt_libuser;
    private javax.swing.JTextField txt_opti;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JPasswordField txt_pass_confirmation;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
